config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'account', to: 'account#index'
  get 'account/removal', to: 'account#cancel'
  devise_for :users, path: 'account', path_names: {
    sign_in: 'login',
    sign_out: 'session',
  }, controllers: {
    registrations: 'users/registrations',
  }
  get 'tasks/completed'
  get 'tasks/pending'
  post 'tasks/filter'
  get 'tasks/by-category/:category_id', to: 'tasks#by_category', as: 'tasks_by_category'
  get 'tasks/by-tags/:tag_ids', to: 'tasks#by_tags', as: 'tasks_by_tags'
  get 'tasks/by-category/:category_id/by-tags/:tag_ids', to: 'tasks#by_category_and_tags', as: 'tasks_by_category_and_tags'
  get 'tasks/search(/:keyword)', to: 'tasks#search', as: 'tasks_search'
  resources :tasks

  get 'settings', to: 'settings#index'
  scope 'settings' do
    resources :tags, :categories
  end

  root 'tasks#index'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true, counter_cache: true
  has_many :tags_tasks, dependent: :destroy
  has_many :tags, through: :tags_tasks

  validates_presence_of :title
  validates_presence_of :user
  validates_inclusion_of :is_done, in: [true, false]
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks.includes([:category, :tags_tasks, :tags]).page(params[:page])
    load_categories include_no_category: true
    load_tags
    parse_group
    sort_tasks
  end

  def completed
    @tasks = current_user.tasks.includes([:category, :tags_tasks, :tags]).where(is_done: true).page(params[:page])
    parse_group
    sort_tasks
  end

  def pending
    @tasks = current_user.tasks.includes([:category, :tags_tasks, :tags]).where(is_done: false).page(params[:page])
    parse_group
    sort_tasks
  end

  def filter
    category = params[:filter][:category] unless params[:filter][:category] == ""
    tags = params[:filter][:tags]
    if category && tags
      redirect_to tasks_by_category_and_tags_path(category, tags.join(','))
    elsif tags
      redirect_to tasks_by_tags_path(tags.join(','))
    elsif category
      redirect_to tasks_by_category_path(category)
    else
      redirect_to tasks_path, notice: "Nebyla vybrána žádná kategorie ani tagy."
    end
  end

  def by_category
    @category = params[:category_id] == "0" ? nil : current_user.categories.find(params[:category_id])
    @tasks = current_user.tasks.includes([:category, :tags_tasks, :tags]).where(category: @category).page(params[:page])
    load_tags
    parse_group
    sort_tasks
  end

  def by_tags
    tag_ids = params[:tag_ids].split(',').map(&:to_i)
    @tags = current_user.tags.find(tag_ids)
    @tasks = current_user.tasks.includes([:category, :tags_tasks, :tags]).where('tags_tasks.tag_id': @tags).page(params[:page])
    load_categories include_no_category: true
    parse_group
    sort_tasks
  end

  def by_category_and_tags
    @category = params[:category_id] == "0" ? nil : current_user.categories.find(params[:category_id])
    tag_ids = params[:tag_ids].split(',').map(&:to_i)
    @tags = current_user.tags.find(tag_ids)
    @tasks = current_user.tasks.includes([:category, :tags_tasks, :tags]).where(category: @category, 'tags_tasks.tag_id': @tags).page(params[:page])
    parse_group
    sort_tasks
  end

  def search
    if params[:search]
      if params[:search][:keyword] != ""
        redirect_to tasks_search_path(params[:search][:keyword])
      else
        redirect_to :tasks, notice: "Nebyl vyhledán žádný text."
      end
    else
      @keyword = params[:keyword]
      @tasks = current_user.tasks.includes([:category, :tags_tasks, :tags]).where("title LIKE ? OR note LIKE ?", "%#{@keyword}%", "%#{@keyword}%").page(params[:page])
      sort_tasks
    end
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end

  def new
    @task = current_user.tasks.new
    load_categories
    load_tags
    save_previous_page
  end

  def edit
    @task = current_user.tasks.find(params[:id])
    @original_task = @task.dup
    load_categories
    load_tags
    save_previous_page
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      redirect_before_form fallback_location: @task, flash: {success: "Úkol byl úspěšně přidán."}
    else
      load_categories
      load_tags
      render 'new'
    end
  end

  def update
    @task = current_user.tasks.find(params[:id])
    @original_task = @task.dup

    if @task.update(task_params)
      if request.patch?
        redirect_back fallback_location: @task, flash: {success: "Úkol byl úspěšně upraven."}
      else
        redirect_before_form fallback_location: @task, flash: {success: "Úkol byl úspěšně upraven."}
      end
    else
      load_categories
      load_tags
      render 'edit'
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy

    referer = begin URI(request.referer).path rescue nil end
    if (referer == task_path(@task))
      redirect_to tasks_path, flash: {success: "Úkol byl úspěšně smazán."}
    else
      redirect_back fallback_location: tasks_path, flash: {success: "Úkol byl úspěšně smazán."}
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :note, :deadline_at, :is_done, :category_id, tag_ids: [])
  end

  def load_categories(opts = {})
    @categories = current_user.categories.order(:title)
    @categories = [Category.new({id: 0, title: "(žádná kategorie)"})] + @categories if opts[:include_no_category]
  end

  def load_tags
    @tags = current_user.tags.order(:title)
  end

  def parse_group
    @group = params.fetch(:group, 0).to_i
  end

  def sort_tasks
    @tasks = @tasks.order('categories.title ASC') if (@group == 1)
    @tasks = @tasks.order('CASE WHEN deadline_at IS NULL THEN 1 ELSE 0 END ASC, deadline_at ASC')
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_list_rows(task)
    if task.category && task.tags.any?
      2
    else
      1
    end
  end
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title, label: 'Název' %>
  <%= f.input :note, label: 'Poznámka' %>
  <%= f.input :deadline_at, as: :datetime, html5: true, label: 'Deadline' %>
  <%= f.input :is_done, as: :boolean, label: 'Označit jako hotovo' %>
  <%= f.association :category, label: 'Kategorie', collection: @categories, include_blank: "(žádná kategorie)", required: false %>
  <%= f.association :tags, label: 'Tagy', collection: @tags, as: :check_boxes, label_method: lambda { |tag| render(partial: 'tags/badge', locals: { tag: tag }).html_safe } %>
  <%= f.button :submit, 'Uložit úkol', class: 'btn-primary' %>
<% end %>

app/views/tasks/_form_category.html.erb
<%= simple_form_for :filter, url: tasks_filter_path, wrapper: :inline_form, html: { class: "form-inline" } do |f| %>
  Z těchto úkolů zobrazit jen úkoly v kategorii
  <%= f.input :category, collection: @categories, include_blank: "(všechny kategorie)", include_hidden: false, required: false, input_html: { class: "form-control-sm mx-2 w-auto" } %>
  <% @tags.each do |tag| %>
    <%= f.hidden_field :tags, multiple: true, value: tag.id %>
  <% end %>
  <%= f.button :submit, "Zobrazit", class: "btn-secondary btn-sm" %>
<% end %>

app/views/tasks/_form_category_and_tags.html.erb
<%= simple_form_for :filter, url: tasks_filter_path, wrapper: :inline_form, html: { class: "form-inline" } do |f| %>
  Zobrazit jen úkoly v kategorii
  <%= f.input :category, collection: @categories, include_blank: "(všechny kategorie)", include_hidden: false, required: false, input_html: { class: "form-control-sm mx-2 w-auto" } %>
  a / nebo jen s tagy
  <%= f.input :tags, collection: @tags, include_hidden: false, required: false, input_html: { class: "form-control-sm mx-2 w-auto", multiple: true, size: 3 } %>
  <%= f.button :submit, "Zobrazit", class: "btn-secondary btn-sm" %>
<% end %>

app/views/tasks/_form_search.html.erb
<%= simple_form_for :search, url: tasks_search_path, method: :get, wrapper: :inline_form, html: { class: "form-inline" } do |f| %>
  Vyhledat v úkolech
  <%= f.input :keyword, as: :string, input_html: { type: "search", class: "form-control-sm mx-2 w-auto" } %>
  <%= f.button :submit, "Hledat", class: "btn-secondary btn-sm" %>
<% end %>

app/views/tasks/_input_search.html.erb
<%= simple_form_for :search, url: tasks_search_path, method: :get, wrapper: :inline_form, html: { class: "form-inline" } do |f| %>
  Vyhledat v úkolech
  <%= f.input :keyword, as: :string, input_html: { type: "search", class: "form-control-sm mx-2" } %>
  <%= f.button :submit, "Hledat", class: "btn-secondary btn-sm" %>
<% end %>

app/views/tasks/_list.html.erb
<% if tasks.any? %>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col" class="d-none d-md-table-cell">ID</th>
        <th scope="col" class="d-md-none p-2"></th>
        <th scope="col">Úkol</th>
        <th scope="col" class="d-none d-md-table-cell">Kategorie a tagy</th>
        <th scope="col" class="d-none d-sm-table-cell">Deadline</th>
        <th scope="col" class="d-none d-lg-table-cell">Datum vytvoření</th>
        <th scope="col" class="d-none d-lg-table-cell">Datum změny</th>
        <th scope="col" style="width: 13rem;"></th>
      </tr>
    </thead>
    <tbody>
      <% tasks.each do |task| %>
        <tr>
          <th scope="row" rowspan="<%= task_list_rows(task) %>" class="d-none d-md-table-cell"><%= task.id %></th>
          <td rowspan="<%= task_list_rows(task) %>" class="d-md-none p-2" style="background-color: <%= task.category ? task.category.color : "transparent" %>;"></td>
          <td rowspan="<%= task_list_rows(task) %>">
            <% if task.is_done %><span title="Hotový úkol">✔️</span><% end %>
            <%= task.title %>
            <% if task.note %><span title="Má poznámku">📝</span><% end %>
          </td>
          <% if task.category %>
            <td class="d-none d-md-table-cell pl-4" style="background: linear-gradient(to right, <%= task.category.color %> 1rem, transparent 1rem);">
              <%= task.category.title %>
            </td>
          <% elsif task.tags.any? %>
            <td class="d-none d-md-table-cell">
              <% task.tags.each do |tag| %>
                <%= render partial: 'tags/badge', locals: { tag: tag } %>
              <% end %>
            </td>
          <% else %>
            <td class="d-none d-md-table-cell"></td>
          <% end %>
          <td rowspan="<%= task_list_rows(task) %>" class="d-none d-sm-table-cell"><%= if task.deadline_at then format_local_datetime task.deadline_at end %></td>
          <td rowspan="<%= task_list_rows(task) %>" class="d-none d-lg-table-cell"><%= format_datetime task.created_at %></td>
          <td rowspan="<%= task_list_rows(task) %>" class="d-none d-lg-table-cell"><%= format_datetime task.updated_at %></td>
          <td rowspan="<%= task_list_rows(task) %>" class="text-right">
            <%= link_to "Označit jako #{task.is_done ? "ne" : ""}hotové", task_path(task.id, task: {is_done: !task.is_done}), method: :patch %><br>
            <%= link_to 'Detail', task_path(task) %> |
            <%= link_to 'Upravit', edit_task_path(task) %> |
            <%= link_to 'Smazat', task_path(task), method: :delete, data: { confirm: 'Opravdu smazat?' } %>
          </td>
        </tr>
        <% if task.category && task.tags.any? %>
          <tr>
            <td class="d-none d-md-table-cell border-top-0 pt-1">
              <% task.tags.each do |tag| %>
                <%= render partial: 'tags/badge', locals: { tag: tag } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate tasks %>
<% else %>
  <p>
    Nejsou tu žádné úkoly. Přidejte si <%= link_to 'nový úkol', new_task_path %>.
  </p>
<% end %>

app/views/tasks/by_category.html.erb
<h1 class="my-3">
  Úkoly
  <% if @category %>
    v kategorii
    <%= render partial: 'categories/badge', locals: { category: @category } %>
  <% else %>
    bez kategorie
  <% end %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Úkoly' => root_path,
    "Dle kategorie: #{@category ? @category.title : "(bez kategorie)"}" => nil,
  }
} %>

<aside class="my-2">
  <%= link_to 'Přidat nový úkol', new_task_path %> |
  Zobrazit <%= link_to 'všechny úkoly', root_path %> |
  <%= link_to "#{@group == 1 ? 'Neseskupovat' : 'Seskupit'} úkoly podle kategorie", group: @group == 1 ? nil : 1 %>
  <%= render 'form_tags' %>
</aside>

<%= render partial: @group == 1 ? 'list_grouped' : 'list', locals: { tasks: @tasks } %>

app/views/tasks/by_category_and_tags.html.erb
<h1 class="my-3">
  Úkoly
  <% if @category %>
    v kategorii
    <%= render partial: 'categories/badge', locals: { category: @category } %>
  <% else %>
    bez kategorie
  <% end %>
  a s tag<%= @tags.size === 1 ? 'em' : 'y' %>
  <% @tags.each do |tag| %>
    <%= render partial: 'tags/badge', locals: { tag: tag } %>
  <% end %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Úkoly' => root_path,
    "Dle kategorie: #{@category ? @category.title : "(bez kategorie)"}" => tasks_by_category_path(@category || 0),
    "Dle kategorie: #{@category ? @category.title : "(bez kategorie)"} a dle tag#{@tags.size === 1 ? 'u' : 'ů'}: #{@tags.map(&:title).join(', ')}" => nil,
  }
} %>

<aside class="my-2">
  <%= link_to 'Přidat nový úkol', new_task_path %> |
  Zobrazit <%= link_to 'všechny úkoly', root_path %> |
  <%= link_to "#{@group == 1 ? 'Neseskupovat' : 'Seskupit'} úkoly podle kategorie", group: @group == 1 ? nil : 1 %>
</aside>

<%= render partial: @group == 1 ? 'list_grouped' : 'list', locals: { tasks: @tasks } %>

app/views/tasks/by_tags.html.erb
<h1 class="my-3">
  Úkoly s tag<%= @tags.size === 1 ? 'em' : 'y' %>
  <% @tags.each do |tag| %>
    <%= render partial: 'tags/badge', locals: { tag: tag } %>
  <% end %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Úkoly' => root_path,
    "Dle tag#{@tags.size === 1 ? 'u' : 'ů'}: #{@tags.map(&:title).join(', ')}" => nil,
  }
} %>

<aside class="my-2">
  <%= link_to 'Přidat nový úkol', new_task_path %> |
  Zobrazit <%= link_to 'všechny úkoly', root_path %> |
  <%= link_to "#{@group == 1 ? 'Neseskupovat' : 'Seskupit'} úkoly podle kategorie", group: @group == 1 ? nil : 1 %>
  <%= render 'form_category' %>
</aside>

<%= render partial: @group == 1 ? 'list_grouped' : 'list', locals: { tasks: @tasks } %>

app/views/tasks/completed.html.erb
<h1 class="my-3">Hotové úkoly</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Úkoly' => root_path,
    'Hotové úkoly' => nil,
  }
} %>

<aside class="my-2">
  <%= link_to 'Přidat nový úkol', new_task_path %> |
  Zobrazit <%= link_to 'všechny', root_path %> nebo <%= link_to 'jen nehotové', tasks_pending_path %> úkoly |
  <%= link_to "#{@group == 1 ? 'Neseskupovat' : 'Seskupit'} úkoly podle kategorie", group: @group == 1 ? nil : 1 %>
</aside>

<%= render partial: @group == 1 ? 'list_grouped' : 'list', locals: { tasks: @tasks } %>

app/views/tasks/edit.html.erb
<h1 class="my-3">
  Upravit úkol:
  <% if @task.is_done %><span title="Hotový úkol">✔️</span><% end %> <%= @task.title %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Úkoly' => root_path,
    @original_task.title => task_path(@task),
    'Upravit úkol' => nil,
  }
} %>

<%= render 'form' %>

<p class="mt-1">
  <%= link_to 'Zrušit', :back %>
</p>

app/views/tasks/index.html.erb
<h1 class="my-3">Úkoly</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Úkoly' => nil,
  }
} %>

<aside class="my-2">
  <%= link_to 'Přidat nový úkol', new_task_path %> |
  Zobrazit <%= link_to 'jen hotové', tasks_completed_path %> nebo <%= link_to 'jen nehotové', tasks_pending_path %> úkoly |
  <%= link_to "#{@group == 1 ? 'Neseskupovat' : 'Seskupit'} úkoly podle kategorie", group: @group == 1 ? nil : 1 %><br>
  <%= render 'form_search' %>
  <%= render 'form_category_and_tags' %>
</aside>

<%= render partial: @group == 1 ? 'list_grouped' : 'list', locals: { tasks: @tasks } %>

app/views/tasks/search.html.erb
<h1 class="my-3">
  Úkoly obsahující <%= @keyword %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Úkoly' => root_path,
    "Vyhledávání: #{@keyword}" => nil,
  }
} %>

<aside class="my-2">
  <%= link_to 'Přidat nový úkol', new_task_path %> |
  Zobrazit <%= link_to 'všechny úkoly', root_path %>
</aside>

<%= render partial: 'list', locals: { tasks: @tasks } %>

app/views/tasks/show.html.erb
<h1 class="my-3">
  Úkol:
  <% if @task.is_done %><span title="Hotový úkol">✔️</span><% end %> <%= @task.title %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Úkoly' => root_path,
    @task.title => nil,
  }
} %>

<div class="card">
  <div class="card-body pb-0">
    <div class="card-title h3"><%= @task.title %></div>
    <h6 class="card-subtitle mb-2">
      <% if @task.is_done %>✔️ Hotový<% else %>❌ Nehotový<% end %> úkol
    </h6>
    <% if @task.note %>
      <p class="card-text"><%= @task.note %></p>
    <% end %>
  </div>
  <ul class="list-group list-group-flush pl-sm-5">
    <li class="list-group-item py-2"><em>ID:</em> <%= @task.id %></li>
    <li class="list-group-item py-2"><em>Kategorie:</em> <%= if @task.category then render partial: 'categories/badge', locals: { category: @task.category } else "(žádná)" end %></li>
    <li class="list-group-item py-2"><em>Tagy:</em>
      <% if @task.tags.any? %>
        <%@task.tags.each do |tag| %>
          <%= render partial: 'tags/badge', locals: { tag: tag } %>
        <% end %>
      <% else %>
        (žádné)
      <% end %>
    </li>
    <li class="list-group-item py-2"><em>Deadline:</em> <%= if @task.deadline_at then format_local_datetime @task.deadline_at else "(žádný)" end %></li>
    <li class="list-group-item py-2"><em>Datum vytvoření:</em> <%= format_datetime @task.created_at %></li>
    <li class="list-group-item py-2"><em>Datum změny:</em> <%= format_datetime @task.updated_at %></li>
  </ul>
  <div class="card-body">
    <%= link_to 'Upravit', edit_task_path(@task), class: 'card-link' %>
    <%= link_to 'Smazat', task_path(@task), method: :delete, data: { confirm: 'Opravdu smazat?' }, class: 'card-link' %>
  </div>
</div>

<p class="mt-1">
  <%= link_to "Zpět", :back %>
</p>