config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'account', to: 'account#index'
  get 'account/removal', to: 'account#cancel'
  devise_for :users, path: 'account', path_names: {
    sign_in: 'login',
    sign_out: 'session',
  }, controllers: {
    registrations: 'users/registrations',
  }
  get 'tasks/completed'
  get 'tasks/pending'
  post 'tasks/filter'
  get 'tasks/by-category/:category_id', to: 'tasks#by_category', as: 'tasks_by_category'
  get 'tasks/by-tags/:tag_ids', to: 'tasks#by_tags', as: 'tasks_by_tags'
  get 'tasks/by-category/:category_id/by-tags/:tag_ids', to: 'tasks#by_category_and_tags', as: 'tasks_by_category_and_tags'
  get 'tasks/search(/:keyword)', to: 'tasks#search', as: 'tasks_search'
  resources :tasks

  get 'settings', to: 'settings#index'
  scope 'settings' do
    resources :tags, :categories
  end

  root 'tasks#index'
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :tags_tasks, dependent: :destroy
  has_many :tasks, through: :tags_tasks

  validates :title, presence: true
  validates :color, presence: true
  validates :user, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = current_user.tags.order(:title)
  end

  def show
    @tag = current_user.tags.find(params[:id])
    @tasks = @tag.tasks.includes([:category, :tags_tasks, :tags]).order('CASE WHEN deadline_at IS NULL THEN 1 ELSE 0 END ASC, deadline_at ASC').page(params[:page])
  end

  def new
    @tag = current_user.tags.new(color: helpers.random_color)
    save_previous_page
  end

  def edit
    @tag = current_user.tags.find(params[:id])
    @original_tag = @tag.dup
    save_previous_page
  end

  def create
    @tag = current_user.tags.new(tag_params)

    if @tag.save
      redirect_before_form fallback_location: @tag, flash: {success: "Tag byl úspěšně přidán."}
    else
      render 'new'
    end
  end

  def update
    @tag = current_user.tags.find(params[:id])
    @original_tag = @tag.dup

    if @tag.update(tag_params)
      redirect_before_form fallback_location: @tag, flash: {success: "Tag byl úspěšně upraven."}
    else
      render 'edit'
    end
  end

  def destroy
    @tag = current_user.tags.find(params[:id])
    @tag.destroy

    redirect_to tags_path, flash: {success: "Tag byl úspěšně smazán."}
  end

  private
  def tag_params
    params.require(:tag).permit(:title, :color)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_badge.html.erb
<span class="badge text-<%= tag.color.paint.light? ? "dark" : "light" %>" style="background-color: <%= tag.color %>;">
  <%= tag.title %>
</span>

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.input :title, label: 'Název' %>
  <%= f.input :color, input_html: { type: "color" }, label: 'Barva' %>
  <%= f.button :submit, 'Uložit tag', class: 'btn-primary' %>
<% end %>

app/views/tags/_list.html.erb
<% if tags.any? %>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col" class="d-none d-md-table-cell">ID</th>
        <th scope="col">Tag</th>
        <th scope="col" class="d-none d-md-table-cell">Barva</th>
        <th scope="col">Úkolů</th>
        <th scope="col" class="d-none d-lg-table-cell">Datum vytvoření</th>
        <th scope="col" class="d-none d-lg-table-cell">Datum změny</th>
        <th scope="col" style="width: 13rem;"></th>
      </tr>
    </thead>
    <tbody>
      <% tags.each do |tag| %>
        <tr>
          <th scope="row" class="d-none d-md-table-cell"><%= tag.id %></th>
          <td><%= render partial: 'badge', locals: { tag: tag } %></td>
          <td class="d-none d-md-table-cell"><%= tag.color %></td>
          <td><%= tag.tasks.size %></td>
          <td class="d-none d-lg-table-cell"><%= format_datetime tag.created_at %></td>
          <td class="d-none d-lg-table-cell"><%= format_datetime tag.updated_at %></td>
          <td class="text-right">
            <%= link_to 'Detail', tag_path(tag) %> |
            <%= link_to 'Upravit', edit_tag_path(tag) %> |
            <%= link_to 'Smazat', tag_path(tag), method: :delete, data: { confirm: 'Opravdu smazat?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    Nejsou tu žádné tagy. Přidejte si <%= link_to 'nový tag', new_tag_path %>.
  </p>
<% end %>

app/views/tags/edit.html.erb
<h1 class="my-3">
  Upravit tag
  <%= render partial: 'badge', locals: { tag: @original_tag } %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Nastavení' => settings_path,
    'Tagy' => tags_path,
    @original_tag.title => tag_path(@tag),
    'Upravit tag' => nil,
  }
} %>

<%= render 'form' %>

<p class="mt-1">
  <%= link_to 'Zrušit', :back %>
</p>

app/views/tags/index.html.erb
<h1 class="my-3">Tagy</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Nastavení' => settings_path,
    'Tagy' => nil,
  }
} %>

<aside class="my-2"><%= link_to 'Přidat nový tag', new_tag_path %></aside>

<%= render partial: 'list', locals: { tags: @tags } %>

app/views/tags/new.html.erb
<h1 class="my-3">Přidat tag</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Nastavení' => settings_path,
    'Tagy' => tags_path,
    'Přidat tag' => nil,
  }
} %>

<%= render 'form' %>

<p class="mt-1">
  <%= link_to 'Zrušit', :back %>
</p>

app/views/tags/show.html.erb
<h1 class="my-3">
  Tag
  <%= render partial: 'badge', locals: { tag: @tag } %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Nastavení' => settings_path,
    'Tagy' => tags_path,
    @tag.title => nil,
  }
} %>

<div class="card">
  <div class="card-body pb-0">
    <div class="card-title h3"><%= render partial: 'badge', locals: { tag: @tag } %></div>
  </div>
  <ul class="list-group list-group-flush pl-sm-5">
    <li class="list-group-item py-2"><em>ID:</em> <%= @tag.id %></li>
    <li class="list-group-item py-2"><em>Barva:</em> <%= @tag.color %></li>
    <li class="list-group-item py-2"><em>Počet úkolů:</em> <%= @tag.tasks.size %></li>
    <li class="list-group-item py-2"><em>Datum vytvoření:</em> <%= format_datetime @tag.created_at %></li>
    <li class="list-group-item py-2"><em>Datum změny:</em> <%= format_datetime @tag.updated_at %></li>
  </ul>
  <div class="card-body">
    <%= link_to 'Upravit', edit_tag_path(@tag), class: 'card-link' %>
    <%= link_to 'Smazat', tag_path(@tag), method: :delete, data: { confirm: 'Opravdu smazat?' }, class: 'card-link' %>
  </div>
</div>

<h2 class="mt-4 h4">Úkoly s tímto tagem</h2>

<%= render partial: 'tasks/list', locals: { tasks: @tasks } %>

<p class="mt-1">
  <%= link_to "Zpět", :back %>
</p>