config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'account', to: 'account#index'
  get 'account/removal', to: 'account#cancel'
  devise_for :users, path: 'account', path_names: {
    sign_in: 'login',
    sign_out: 'session',
  }, controllers: {
    registrations: 'users/registrations',
  }
  get 'tasks/completed'
  get 'tasks/pending'
  post 'tasks/filter'
  get 'tasks/by-category/:category_id', to: 'tasks#by_category', as: 'tasks_by_category'
  get 'tasks/by-tags/:tag_ids', to: 'tasks#by_tags', as: 'tasks_by_tags'
  get 'tasks/by-category/:category_id/by-tags/:tag_ids', to: 'tasks#by_category_and_tags', as: 'tasks_by_category_and_tags'
  get 'tasks/search(/:keyword)', to: 'tasks#search', as: 'tasks_search'
  resources :tasks

  get 'settings', to: 'settings#index'
  scope 'settings' do
    resources :tags, :categories
  end

  root 'tasks#index'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks

  validates :title, presence: true
  validates :color, presence: true
  validates :user, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories.order(:title)
  end

  def show
    @category = current_user.categories.find(params[:id])
    @tasks = @category.tasks.includes([:tags_tasks, :tags]).order('CASE WHEN deadline_at IS NULL THEN 1 ELSE 0 END ASC, deadline_at ASC').page(params[:page])
  end

  def new
    @category = current_user.categories.new(color: helpers.random_color)
    save_previous_page
  end

  def edit
    @category = current_user.categories.find(params[:id])
    @original_category = @category.dup
    save_previous_page
  end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_before_form fallback_location: @category, flash: {success: "Kategorie byla úspěšně přidána."}
    else
      render 'new'
    end
  end

  def update
    @category = current_user.categories.find(params[:id])
    @original_category = @category.dup

    if @category.update(category_params)
      redirect_before_form fallback_location: @category, flash: {success: "Kategorie byla úspěšně upravena."}
    else
      render 'edit'
    end
  end

  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy

    redirect_to categories_path, flash: {success: "Kategorie byla úspěšně smazána."}
  end

  private
  def category_params
    params.require(:category).permit(:title, :color)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_badge.html.erb
<span style="color: <%= category.color %>;">█</span>
<%= category.title %>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.input :title, label: 'Název' %>
  <%= f.input :color, input_html: { type: "color" }, label: 'Barva' %>
  <%= f.button :submit, 'Uložit kategorii', class: 'btn-primary' %>
<% end %>

app/views/categories/_list.html.erb
<% if categories.any? %>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col" class="d-none d-md-table-cell">ID</th>
        <th scope="col">Kategorie</th>
        <th scope="col" class="d-none d-md-table-cell">Barva</th>
        <th scope="col">Úkolů</th>
        <th scope="col" class="d-none d-lg-table-cell">Datum vytvoření</th>
        <th scope="col" class="d-none d-lg-table-cell">Datum změny</th>
        <th scope="col" style="width: 13rem;"></th>
      </tr>
    </thead>
    <tbody>
      <% categories.each do |category| %>
        <tr>
          <th scope="row" class="d-none d-md-table-cell"><%= category.id %></th>
          <td class="pl-4" style="background: linear-gradient(to right, <%= category.color %> 1rem, transparent 1rem);"><%= category.title %></td>
          <td class="d-none d-md-table-cell"><%= category.color %></td>
          <td><%= category.tasks.size %></td>
          <td class="d-none d-lg-table-cell"><%= format_datetime category.created_at %></td>
          <td class="d-none d-lg-table-cell"><%= format_datetime category.updated_at %></td>
          <td class="text-right">
            <%= link_to 'Detail', category_path(category) %> |
            <%= link_to 'Upravit', edit_category_path(category) %> |
            <%= link_to 'Smazat', category_path(category), method: :delete, data: { confirm: 'Opravdu smazat?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    Nejsou tu žádné kategorie. Přidejte si <%= link_to 'novou kategorii', new_category_path %>.
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1 class="my-3">
  Upravit kategorii
  <%= render partial: 'badge', locals: { category: @original_category } %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Nastavení' => settings_path,
    'Kategorie' => categories_path,
    @original_category.title => category_path(@category),
    'Upravit kategorii' => nil,
  }
} %>

<%= render 'form' %>

<p class="mt-1">
  <%= link_to 'Zrušit', :back %>
</p>

app/views/categories/index.html.erb
<h1 class="my-3">Kategorie</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Nastavení' => settings_path,
    'Kategorie' => nil,
  }
} %>

<aside class="my-2"><%= link_to 'Přidat novou kategorii', new_category_path %></aside>

<%= render partial: 'list', locals: { categories: @categories } %>

app/views/categories/new.html.erb
<h1 class="my-3">Přidat kategorii</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Nastavení' => settings_path,
    'Kategorie' => categories_path,
    'Přidat kategorii' => nil,
  }
} %>

<%= render 'form' %>

<p class="mt-1">
  <%= link_to 'Zrušit', :back %>
</p>

app/views/categories/show.html.erb
<h1 class="my-3">
  Kategorie
  <%= render partial: 'badge', locals: { category: @category } %>
</h1>

<%= render 'flash_messages' %>
<%= render partial: 'breadcrumb', locals: {
  breadcrumb: {
    'Nastavení' => settings_path,
    'Kategorie' => categories_path,
    @category.title => nil,
  }
} %>

<div class="card">
  <div class="card-body pb-0">
    <div class="card-title h3"><%= render partial: 'badge', locals: { category: @category } %></div>
  </div>
  <ul class="list-group list-group-flush pl-sm-5">
    <li class="list-group-item py-2"><em>ID:</em> <%= @category.id %></li>
    <li class="list-group-item py-2"><em>Barva:</em> <%= @category.color %></li>
    <li class="list-group-item py-2"><em>Počet úkolů:</em> <%= @category.tasks.size %></li>
    <li class="list-group-item py-2"><em>Datum vytvoření:</em> <%= format_datetime @category.created_at %></li>
    <li class="list-group-item py-2"><em>Datum změny:</em> <%= format_datetime @category.updated_at %></li>
  </ul>
  <div class="card-body">
    <%= link_to 'Upravit', edit_category_path(@category), class: 'card-link' %>
    <%= link_to 'Smazat', category_path(@category), method: :delete, data: { confirm: 'Opravdu smazat?' }, class: 'card-link' %>
  </div>
</div>

<h2 class="mt-4 h4">Úkoly v této kategorii</h2>

<%= render partial: 'tasks/list', locals: { tasks: @tasks } %>

<p class="mt-1">
  <%= link_to "Zpět", :back %>
</p>