config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'account', to: 'account#index'
  get 'account/removal', to: 'account#cancel'
  devise_for :users, path: 'account', path_names: {
    sign_in: 'login',
    sign_out: 'session',
  }, controllers: {
    registrations: 'users/registrations',
  }
  get 'tasks/completed'
  get 'tasks/pending'
  post 'tasks/filter'
  get 'tasks/by-category/:category_id', to: 'tasks#by_category', as: 'tasks_by_category'
  get 'tasks/by-tags/:tag_ids', to: 'tasks#by_tags', as: 'tasks_by_tags'
  get 'tasks/by-category/:category_id/by-tags/:tag_ids', to: 'tasks#by_category_and_tags', as: 'tasks_by_category_and_tags'
  get 'tasks/search(/:keyword)', to: 'tasks#search', as: 'tasks_search'
  resources :tasks

  get 'settings', to: 'settings#index'
  scope 'settings' do
    resources :tags, :categories
  end

  root 'tasks#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="cs">
  <head>
    <title>Správa úkolů</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-expand-md navbar-dark bg-primary">
      <div class="container">
        <%= link_to 'Správa úkolů', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <nav class="collapse navbar-collapse ml-3 flex-grow-1" id="navbarNav">
          <ul class="navbar-nav flex-grow-1 align-items-md-center">
            <% if user_signed_in? %>
              <li class="nav-item flex-shrink-0<% if controller_name == 'tasks' %> active<% end %>">
                <%= link_to 'Úkoly', root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item flex-shrink-0<% if controller_name.in? ['settings', 'categories', 'tags'] %> active<% end %>">
                <%= link_to 'Nastavení', settings_path, class: 'nav-link' %>
              </li>
              <li class="nav-item flex-shrink-0<% if controller_name.in? ['account', 'registrations'] %> active<% end %> mr-auto">
                <%= link_to 'Můj účet', account_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <div class="py-2 px-md-2 text-light text-md-right font-italic">
                  <%= current_user.username %>
                </div>
              </li>
              <li class="nav-item flex-shrink-0">
                <%= link_to 'Odhlásit se', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item <%= "active" if controller_name == 'sessions' %>">
                <%= link_to 'Přihlásit se', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item <%= "active" if controller_name == 'registrations' %>">
                <%= link_to 'Zaregistrovat se', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <main class="container">
      <%= yield %>
    </main>

    <footer class="bg-light">
      <div class="container p-1">
        Domácí úkol Webové technologie - Kate Miháliková
      </div>
    </footer>
  </body>
</html>